In [1]:
import numpy as np
from collections import namedtuple
import random

In [42]:
info = namedtuple( 'info', ['cost', 'position'] )

position_size = 5
swarm_size = 6
low = 0 # we want our solution to be bounded between 0 to 100
high = 100
vmin = -200
vmax = 200
w = 0.7 # Inertia weight to prevent velocities becoming too large
c1 = 2 # Scaling co-efficient on the social component
c2 = 2 # Scaling co-efficient on the cognitive component

# start with a random velocity between 0 and 1
array_size = swarm_size, position_size
velocity = np.random.random(array_size)
swarm = np.random.randint(low, high + 1, array_size)
swarm

array([[90, 40, 79,  5, 57],
       [40, 99, 59, 73, 71],
       [76, 96, 15, 39, 65],
       [51, 45, 98, 43, 78],
       [13,  8, 46, 70, 52],
       [63, 79, 99, 98, 55]])

In [43]:
# determine the cost of an chromosome. lower is better
target = 200
cost = np.abs( np.sum( swarm, axis = 1 ) - target )

# combine the cost and chromosome into one list

graded = [ info( c, list(s) ) for s, c in zip(swarm, cost) ]
graded_swarm = sorted(graded)
swarm = np.array([ gs.position for gs in graded_swarm ])

In [44]:
graded_swarm

[info(cost=11, position=[13, 8, 46, 70, 52]),
 info(cost=71, position=[90, 40, 79, 5, 57]),
 info(cost=91, position=[76, 96, 15, 39, 65]),
 info(cost=115, position=[51, 45, 98, 43, 78]),
 info(cost=142, position=[40, 99, 59, 73, 71]),
 info(cost=194, position=[63, 79, 99, 98, 55])]

In [37]:
swarm

array([[ 41.,  21.,  18.,  29.,  40.],
       [  2.,  32.,  15.,  43.,  53.],
       [ 52.,  28.,   1.,  45.,  51.],
       [ 52.,  22.,  48.,  15.,  24.],
       [  4.,   4.,  23.,  33.,  41.],
       [ 28.,  43.,  11.,  25.,   3.]])

In [38]:
pbest_new = np.array([position for cost, position in graded_swarm])
gbest_new = graded_swarm[0]

In [47]:
np.array(graded_swarm[0].position)

array([13,  8, 46, 70, 52])

In [52]:
graded_swarm1 = graded_swarm.copy()

In [57]:
graded_swarm1[0] = info( 1, [12, 11, 10, 9, 20] )

In [58]:
graded_swarm1

[info(cost=1, position=[12, 11, 10, 9, 20]),
 info(cost=71, position=[90, 40, 79, 5, 57]),
 info(cost=91, position=[76, 96, 15, 39, 65]),
 info(cost=115, position=[51, 45, 98, 43, 78]),
 info(cost=142, position=[40, 99, 59, 73, 71]),
 info(cost=194, position=[63, 79, 99, 98, 55])]

In [39]:
pbest_new

array([[ 52.,  28.,   1.,  45.,  51.],
       [ 52.,  22.,  48.,  15.,  24.],
       [ 41.,  21.,  18.,  29.,  40.],
       [  2.,  32.,  15.,  43.,  53.],
       [ 28.,  43.,  11.,  25.,   3.],
       [  4.,   4.,  23.,  33.,  41.]])

In [33]:
pbest

array([[ 41,  21,  18,  28,  40],
       [ 87,  84,  57,  11,  25],
       [ 28,  14,  38,   9,  28],
       [ 29,  72,  97,  44,  59],
       [ 94,  51,  67, 100,  39],
       [ 57,  97,  52,  91,  84]])

In [26]:
swarm

array([[ 41,  21,  18,  28,  40],
       [ 87,  84,  57,  11,  25],
       [ 28,  14,  38,   9,  28],
       [ 29,  72,  97,  44,  59],
       [ 94,  51,  67, 100,  39],
       [ 57,  97,  52,  91,  84]])

In [10]:
# pbest, keeps track of each individual's best
# gbest, keeps track of swarm's best

gbest_old = np.inf
gbest_new = graded[0].cost
if gbest_new > gbest_old:
    gbest = gbest_

info(cost=10, position=[89, 67, 15, 3, 36])

In [27]:
pbest - swarm

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [28]:
r1 = random.random()
cognitive = c1 * r1 * (pbest - swarm)
cognitive

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [29]:
r2 = random.random()
social = c2 * r2 * (gbest - swarm)
social

array([[   0.        ,    0.        ,    0.        ,    0.        ,    0.        ],
       [ -85.06987536, -116.50874235,  -72.12445955,   31.43886698,
          27.74017675],
       [  24.04148652,   12.94541582,  -36.98690233,   35.13755722,
          22.1921414 ],
       [  22.1921414 ,  -94.31660095, -146.09826421,  -29.58952187,
         -35.13755722],
       [ -98.01529118,  -55.4803535 ,  -90.61791071, -133.1528484 ,
           1.84934512],
       [ -29.58952187, -140.55022886,  -62.87773396, -116.50874235,
         -81.37118513]])

In [30]:
# update velocity
velocity = w * velocity + cognitive + social

# constraint on velocity
velocity[velocity > vmax] = vmax
velocity[velocity < vmin] = vmin

In [31]:
# update position (round all positions)
swarm = np.round(swarm + velocity)

# constraint on position
# if there's any element that exceeds the upper and lower bound
# by a certain amount, ricochet back from the border by that amount
exceed = swarm > high
if np.sum(exceed):
    exceed_amount = swarm[exceed] - high
    swarm[exceed] = high - exceed_amount
    
exceed = swarm < low
if np.sum(exceed):
    exceed_amount = low - swarm[exceed]
    swarm[exceed] = low + exceed_amount

swarm

array([[ 41.,  21.,  18.,  29.,  40.],
       [  2.,  32.,  15.,  43.,  53.],
       [ 52.,  28.,   1.,  45.,  51.],
       [ 52.,  22.,  48.,  15.,  24.],
       [  4.,   4.,  23.,  33.,  41.],
       [ 28.,  43.,  11.,  25.,   3.]])

- http://www.turingfinance.com/portfolio-optimization-using-particle-swarm-optimization/
- http://web.ist.utl.pt/gdgp/VA/pso.htm