http://chairnerd.seatgeek.com/fuzzywuzzy-fuzzy-string-matching-in-python/

https://marcobonzanini.com/2015/02/25/fuzzy-string-matching-in-python/

http://www.python-course.eu/levenshtein_distance.php

The minimum edit distance between two strings is the minimum numer of editing operations needed to convert one string into another. The editing operations can consist of insertions, deletions and substitutions. e.g. The minimum edit distance between the two strings "Mannhaton" and "Manhattan" corresponds to the value 3, as we need three basic editing operation to transform the first one into the second one:

In [1]:
# deletion (n)
s = "Mannhaton"
s = s[:2] + s[3:]
print(s)

# insertion (t)
s = s[:5] + "t" + s[5:]
print(s)

# substitution (o with a)
s = s[:7] + "a" + s[8:]
print(s)

Manhaton
Manhatton
Manhattan


In [2]:
import numpy as np

query = 'flaw'
target = 'lawn'
n_rows = len(query) + 1
n_cols = len(target) + 1
np.arange(1, n_rows)

array([1, 2, 3, 4])

In [11]:
import numpy as np

query = 'flaw'
target = 'lawns'
n_rows = len(query) + 1
n_cols = len(target) + 1

dist = np.zeros((n_rows, n_cols))
dist[0, 1:] = np.arange(1, n_cols)
dist[1:, 0] = np.arange(1, n_rows)

In [12]:
dist

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 2.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0.,  0.],
       [ 4.,  0.,  0.,  0.,  0.,  0.]])

In [15]:
min(100, 23, 45)

23

In [8]:
np.arange(1, n_rows)

array([1, 2, 3, 4])

In [6]:
dist

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])