$$ output = \begin{cases} 1 \text{, if } wx + b > 0  \\ 
    0 \text{, if}\ wx + b \leq 0 \end{cases} $$

# Neural Networks

The goal in training a neural network is to find the set of weights and biases that minimize the cost function.


**Side Note on standard error output:** 

In particular, `stdout` should be used for normal program output ( this is where prints usually goes to ), whereas `stderr` should be reserved only for error messages (abnormal program execution).

In [1]:
from scipy.special import expit # equivalent to the sigmoid function
import numpy as np
import sys
sys.stderr.write('test')
sys.stderr.flush()

test

In [2]:
import random
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.cross_validation import train_test_split

iris = datasets.load_iris()
X = iris.data[ :, [ 2, 3 ] ]
y = iris.target
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size = 0.3, random_state = 0 )

sc = StandardScaler()
X_train_sd = sc.fit_transform(X_train)
X_test_sd  = sc.transform(X_test)

In [3]:
def _encode_labels( y, n_output ):
    onehot = np.zeros( [ y.shape[0], n_output ] )
    for idx, val in enumerate(y):
        onehot[idx, val] = 1.0
    return onehot

In [7]:
X_data, y_data = X.copy(), y.copy()
y_enc = _encode_labels( y_train, n_output )

w1 = np.random.uniform( -1.0, 1.0, size = n_hidden * (n_features + 1) )
w1 = w1.reshape(n_hidden, n_features + 1)

In [39]:
import neuralnet as nn
reload(nn)

# parameters
n_output = 3
n_hidden = 2
n_features = X_train.shape[1]

nn1 = nn.NeuralNetMLP( n_output = n_output, 
                       n_features = n_features, 
                       n_hidden = n_hidden, 
                       l2 = 0.1, 
                       l1 = 0.0, 
                       epochs = 10, 
                       eta = 0.001,
                       alpha = 0.001,
                       decrease_const = 0.00001,
                       minibatches = 5, 
                       shuffle = False,
                       random_state = 1 )

nn1.fit( X_train, y_train, print_progress = True )

Epoch: 10/10

In [27]:
idx = np.array_split( range(y_data.shape[0]), 10)[1]
X = X_data[idx]

a1 = np.hstack( ( np.ones([ X.shape[0], 1]), X ) )
z2 = nn1.w1.dot( a1.T )
a2 = expit(z2)
a2 = np.vstack( ( np.ones([ 1, a2.shape[1]]), a2 ) )
z3 = nn1.w2.dot(a2)
a3 = expit(z3).T # activation for the output

In [57]:
a3

array([[ 0.30597158,  0.51159518,  0.4179317 ],
       [ 0.30661256,  0.51417982,  0.40969228],
       [ 0.30419264,  0.51286642,  0.41593958],
       [ 0.30323999,  0.50904606,  0.42819349],
       [ 0.30389115,  0.51154972,  0.42012562],
       [ 0.30122446,  0.50898303,  0.43039906],
       [ 0.30597158,  0.51159518,  0.4179317 ],
       [ 0.3029821 ,  0.51883005,  0.39964838],
       [ 0.30727954,  0.50936565,  0.42323181],
       [ 0.30058767,  0.50657384,  0.43822028],
       [ 0.30152352,  0.51025381,  0.42632397],
       [ 0.30562426,  0.51036513,  0.42191081],
       [ 0.30180825,  0.51156948,  0.42214004],
       [ 0.30207759,  0.51293047,  0.41784845],
       [ 0.30152352,  0.51025381,  0.42632397]])

In [56]:
np.argmax( a3, axis = 1 )

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [51]:
nn1._add_bias_unit(z2, how='row').dot(sigma3) * 

array([[-0.44548958,  0.66995764,  3.31586115],
       [-0.1389285 ,  0.1040963 ,  0.79740744],
       [ 0.90660048, -0.73018712, -6.25275145]])

In [50]:
sigma3 = a3 - y_enc[idx, : ]