<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [6]:
import numpy as np
from operator import itemgetter
point_list = [(2,3), (5,4), (9,6), (4,7), (8,1), (7,2)]
d = 2

point_list

[(2, 3), (5, 4), (9, 6), (4, 7), (8, 1), (7, 2)]

In [7]:
depth = 0
axis = depth % d
 
# Sort point list and choose median as pivot element
point_list.sort(key = itemgetter(axis))
median = len(point_list) // 2
median

3

In [8]:
point_list

[(2, 3), (4, 7), (5, 4), (7, 2), (8, 1), (9, 6)]

In [41]:
K = 11
n_row = 10000
n_col = 12
data = 10 * np.random.rand(n_row * n_col).reshape((n_col, n_row))

# row is the features, col is the observations
data = np.array([(2,3), (5,4), (9,6), (4,7), (8,1), (7,2)]).T
print(data.shape)
data

(2, 6)


array([[2, 5, 9, 4, 8, 7],
       [3, 4, 6, 7, 1, 2]])

In [43]:
n_col, n_row = data.shape

# find bounding hyper-rectangle, the
# minimum and maximum of each features
# is stored in each column
hrect = np.zeros((2, n_col))
hrect[0] = np.min(data, axis = 1)
hrect[1] = np.max(data, axis = 1)
hrect

array([[ 2.,  1.],
       [ 9.,  7.]])

In [44]:
# create the root node by
# sorting on the first feature
idx = np.argsort(data[0])
data = data[:, idx]
data

array([[2, 4, 5, 7, 8, 9],
       [3, 7, 4, 2, 1, 6]])

In [46]:
# obtain the splitting value
splitval = data[0, n_row // 2]
splitval

7

In [47]:
# create the left and right hyper-rectangle
# where the left is smaller than the split value
left_hrect = hrect.copy()
right_hrect = hrect.copy()
left_hrect[1, 0] = splitval
right_hrect[0, 0] = splitval
left_hrect

array([[ 2.,  1.],
       [ 7.,  7.]])

In [48]:
right_hrect

array([[ 7.,  1.],
       [ 9.,  7.]])

In [55]:
tree = [(None, None, left_hrect, right_hrect, None, None)]

# stack stores the splitted data, indices, the depth of the tree
# the parent (length of tree?), whether it's a left branch or not
mid = n_row // 2
stack = [(data[:, :mid], idx[:mid], 1, 0, True),
         (data[:, mid:], idx[mid:], 1, 0, False)]
stack

[(array([[2, 4, 5],
         [3, 7, 4]]), array([0, 3, 1]), 1, 0, True), (array([[7, 8, 9],
         [2, 1, 6]]), array([5, 4, 2]), 1, 0, False)]

In [57]:
data, didx, depth, parent, left_branch = stack.pop()
ndata = data.shape[1]
nodeptr = len(tree)
nodeptr

1

In [64]:
idx

array([0, 3, 1, 5, 4, 2])

In [61]:
_didx, _data, _left_hrect, _right_hrect, left, right = tree[parent]

In [62]:
tree[parent]

(None, None, array([[ 2.,  1.],
        [ 7.,  7.]]), array([[ 7.,  1.],
        [ 9.,  7.]]), None, None)

In [65]:
tree

[(None, None, array([[ 2.,  1.],
         [ 7.,  7.]]), array([[ 7.,  1.],
         [ 9.,  7.]]), None, None)]

In [69]:
left

In [68]:
tree

[(None, None, array([[ 2.,  1.],
         [ 7.,  7.]]), array([[ 7.,  1.],
         [ 9.,  7.]]), None, 1)]

In [67]:
tree[parent] = (_didx, _data, _left_hrect, _right_hrect, nodeptr, right) if left_branch \
            else (_didx, _data, _left_hrect, _right_hrect, left, nodeptr)


In [ ]:
knn_search(data, K)