# Table of Contents
 <p><div class="lev2 toc-item"><a href="#Boxcox" data-toc-modified-id="Boxcox-01"><span class="toc-item-num">0.1&nbsp;&nbsp;</span>Boxcox</a></div><div class="lev1 toc-item"><a href="#Reference" data-toc-modified-id="Reference-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Reference</a></div>

In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import Imputer

In [3]:
# Create an empty dataset
df = pd.DataFrame()

# Create two variables called x0 and x1. Make the first value of x1 a missing value
df['x0'] = [0.3051, 0.4949, 0.6974, 0.3769, 0.2231, 0.341, 0.4436, 0.5897, 0.6308, 0.5]
df['x1'] = [np.nan, 0.2654, 0.2615, 0.5846, 0.4615, 0.8308, 0.4962, 0.3269, 0.5346, 0.6731]

# View the dataset
df

x0      x1
0  0.3051     NaN
1  0.4949  0.2654
2  0.6974  0.2615
3  0.3769  0.5846
4  0.2231  0.4615
5  0.3410  0.8308
6  0.4436  0.4962
7  0.5897  0.3269
8  0.6308  0.5346
9  0.5000  0.6731

In [7]:
# Create an imputer object that looks for 'Nan' values,
# then replaces them with the mean value of the feature by columns (axis=0)
imputer = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0)
imputed_df = imputer.fit_transform(df.values)
imputed_df

array([[ 0.3051    ,  0.49273333],
       [ 0.4949    ,  0.2654    ],
       [ 0.6974    ,  0.2615    ],
       [ 0.3769    ,  0.5846    ],
       [ 0.2231    ,  0.4615    ],
       [ 0.341     ,  0.8308    ],
       [ 0.4436    ,  0.4962    ],
       [ 0.5897    ,  0.3269    ],
       [ 0.6308    ,  0.5346    ],
       [ 0.5       ,  0.6731    ]])

In [8]:
np.mean(df['x1'])

0.4927333333333333

In [ ]:
strategy = {
    'mode':
    'median': 
}

In [17]:
def _get_mask(X, value_to_mask):
    """Compute the boolean mask X == missing_values."""
    if value_to_mask == "NaN" or np.isnan(value_to_mask):
        return np.isnan(X)
    else:
        return X == value_to_mask

In [62]:
import numpy.ma as ma

X = df.values
mask = _get_mask(X, 'NaN')
masked_X = np.ma.masked_array(X, mask = mask)
mean_masked = ma.mean(masked_X, axis = 0)
# Avoid the warning "Warning: converting a masked element to nan."
mean = np.ma.getdata(mean_masked)
mean[np.ma.getmask(mean_masked)] = np.nan
mean

array([ 0.46025   ,  0.49273333])

In [81]:
mask

array([[False,  True],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False]], dtype=bool)

In [93]:
mask[:, 1]

array([ True, False, False, False, False, False, False, False, False, False], dtype=bool)

In [94]:
X

array([[ 0.3051,     nan],
       [ 0.4949,  0.2654],
       [ 0.6974,  0.2615],
       [ 0.3769,  0.5846],
       [ 0.2231,  0.4615],
       [ 0.341 ,  0.8308],
       [ 0.4436,  0.4962],
       [ 0.5897,  0.3269],
       [ 0.6308,  0.5346],
       [ 0.5   ,  0.6731]])

In [92]:
X[mask[:, 1]]

array([[ 0.3051,     nan]])

# Reference

- [Blog: Impute Missing Values With Means](https://chrisalbon.com/machine-learning/impute_missing_values_with_means.html)